### ISSUE TITLE
使用click标签，出现浏览器crash

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#5]
当被click元素display为none时，浏览器直接crash，然后又重启

**Comment by shenruisi** [comment]
Fixed with commit [465c8b8](https://github.com/shenruisi/salyut/commit/465c8b8e25a880c44805b6c689ebbf19a6a4ab98) branch [release-0.0.8-rc1](https://github.com/shenruisi/salyut/tree/release-0.0.8-rc1)

**Comment by shenruisi** [comment]
> 当被click元素display为none时，浏览器直接crash，然后又重启

Fixed with commit [465c8b8](https://github.com/shenruisi/salyut/commit/465c8b8e25a880c44805b6c689ebbf19a6a4ab98) branch [release-0.0.8-rc1](https://github.com/shenruisi/salyut/tree/release-0.0.8-rc1)
